### ISSUE TITLE
input.def: meta Data format

### ISSUE THREAD

**Issue by mscheinert** [mscheinert/simsar#2]
Would be nice to have multiple checksum types and/or a more flexible structure (RJSON/YAML?) for `input.def`:

```yaml
{
    'ORCA_R2_zps_domcfg.nc': {
        CHECKSUM: {
            SHA256: 736500c34b2f5959070d961ca64a0649895cfa27101368eff90edb7f90c5097f,
            M5: ''
        },
        DOI: '10.5281/zenodo.3767939',
        URL: {
            'https://zenodo.org/record/3767939/files/ORCA2_ICE_v4.2.tar?download=1'
        },
        COMMENT: "This file contains the horizontal and vertical grid for ORCA2"
    }
}
```
